rmdir /s /q LibItunesXmlDb\obj
rmdir /s /q ListerPlugin\Debug
rmdir /s /q ListerPlugin\Release
rmdir /s /q ListerPlugin\x64
rmdir /s /q ManagedBass\bin
rmdir /s /q ManagedBass\Windows\obj
rmdir /s /q PackerPlugin\Debug
rmdir /s /q PackerPlugin\Release
rmdir /s /q PackerPlugin\x64
rmdir /s /q TCPlayer\obj