<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TcPlayer.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ManagedBass" Version="3.1.1" />
    <PackageReference Include="ManagedBass.Mix" Version="3.1.1" />
    <PackageReference Include="ManagedBass.Wasapi" Version="3.1.1" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TcPlayer.Native\TcPlayer.Native.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Internals\" />
  </ItemGroup>

</Project>
