//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Website.
        /// </summary>
        public static string About_VisitWebsite {
            get {
                return ResourceManager.GetString("About_VisitWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent URLs:.
        /// </summary>
        public static string AddURL_Recent {
            get {
                return ResourceManager.GetString("AddURL_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        public static string AddURL_URL {
            get {
                return ResourceManager.GetString("AddURL_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to begining.
        /// </summary>
        public static string Chapters_Begin {
            get {
                return ResourceManager.GetString("Chapters_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to {0}.
        /// </summary>
        public static string Chapters_Jumpto {
            get {
                return ResourceManager.GetString("Chapters_Jumpto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Rate: .
        /// </summary>
        public static string DeviceChange_SampleRate {
            get {
                return ResourceManager.GetString("DeviceChange_SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select output device:.
        /// </summary>
        public static string DeviceChange_SelectLabel {
            get {
                return ResourceManager.GetString("DeviceChange_SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///Bass Error code: {1}
        ///Error Description: {2}.
        /// </summary>
        public static string Engine_Error {
            get {
                return ResourceManager.GetString("Engine_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.dll init failed.
        /// </summary>
        public static string Engine_ErrorBass {
            get {
                return ResourceManager.GetString("Engine_ErrorBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer stream create failed.
        /// </summary>
        public static string Engine_ErrorMixer {
            get {
                return ResourceManager.GetString("Engine_ErrorMixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer channel add failed.
        /// </summary>
        public static string Engine_ErrorMixerChannel {
            get {
                return ResourceManager.GetString("Engine_ErrorMixerChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound font is missing, or not set. MIDI playback is not possible..
        /// </summary>
        public static string Engine_ErrorSoundfont {
            get {
                return ResourceManager.GetString("Engine_ErrorSoundfont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Equalizer_Reset {
            get {
                return ResourceManager.GetString("Equalizer_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.dll components are corrupted. Please reinstall program..
        /// </summary>
        public static string Error_CorruptDll {
            get {
                return ResourceManager.GetString("Error_CorruptDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details: .
        /// </summary>
        public static string Error_Details {
            get {
                return ResourceManager.GetString("Error_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Error.
        /// </summary>
        public static string Error_Download {
            get {
                return ResourceManager.GetString("Error_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Load error.
        /// </summary>
        public static string Error_FileLoad {
            get {
                return ResourceManager.GetString("Error_FileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string iTunes_Albums {
            get {
                return ResourceManager.GetString("iTunes_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string iTunes_Artists {
            get {
                return ResourceManager.GetString("iTunes_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string iTunes_Genres {
            get {
                return ResourceManager.GetString("iTunes_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string iTunes_Playlists {
            get {
                return ResourceManager.GetString("iTunes_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string iTunes_Years {
            get {
                return ResourceManager.GetString("iTunes_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ....
        /// </summary>
        public static string MainWin_About {
            get {
                return ResourceManager.GetString("MainWin_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always top: off.
        /// </summary>
        public static string MainWin_AlwaysTopDisabled {
            get {
                return ResourceManager.GetString("MainWin_AlwaysTopDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always top: on.
        /// </summary>
        public static string MainWin_AlwaysTopEnabled {
            get {
                return ResourceManager.GetString("MainWin_AlwaysTopEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Change output device... ].
        /// </summary>
        public static string MainWin_ChangeDevice {
            get {
                return ResourceManager.GetString("MainWin_ChangeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media keys are in use by another application.
        ///To Use media key functions please close other apps that may use the keys, then restart the player.
        /// </summary>
        public static string MainWin_ErrorMediaKeys {
            get {
                return ResourceManager.GetString("MainWin_ErrorMediaKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application.
        /// </summary>
        public static string MainWin_ExitApp {
            get {
                return ResourceManager.GetString("MainWin_ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit confirmation.
        /// </summary>
        public static string MainWin_ExitConfirmTitle {
            get {
                return ResourceManager.GetString("MainWin_ExitConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit program?.
        /// </summary>
        public static string MainWin_ExtitConfirmMessage {
            get {
                return ResourceManager.GetString("MainWin_ExtitConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List: .
        /// </summary>
        public static string MainWin_ListLabel {
            get {
                return ResourceManager.GetString("MainWin_ListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to Tray.
        /// </summary>
        public static string MainWin_Minimize {
            get {
                return ResourceManager.GetString("MainWin_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Player ].
        /// </summary>
        public static string MainWin_PlayerTab {
            get {
                return ResourceManager.GetString("MainWin_PlayerTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Playlist ].
        /// </summary>
        public static string MainWin_PlaylistTab {
            get {
                return ResourceManager.GetString("MainWin_PlaylistTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Radio ].
        /// </summary>
        public static string MainWin_RadioTab {
            get {
                return ResourceManager.GetString("MainWin_RadioTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings ....
        /// </summary>
        public static string MainWin_Settings {
            get {
                return ResourceManager.GetString("MainWin_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Player {0}.
        /// </summary>
        public static string MainWin_Title {
            get {
                return ResourceManager.GetString("MainWin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Artist....
        /// </summary>
        public static string NetMenu_SearchArtist {
            get {
                return ResourceManager.GetString("NetMenu_SearchArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Song....
        /// </summary>
        public static string NetMenu_SearchSong {
            get {
                return ResourceManager.GetString("NetMenu_SearchSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Player is running.
        /// </summary>
        public static string Notify_Text {
            get {
                return ResourceManager.GetString("Notify_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing.
        /// </summary>
        public static string Notify_Title {
            get {
                return ResourceManager.GetString("Notify_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Chapters ].
        /// </summary>
        public static string PlayerTab_ButtonChapters {
            get {
                return ResourceManager.GetString("PlayerTab_ButtonChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute / Unmute.
        /// </summary>
        public static string PlayerTab_ButtonMuteUnmute {
            get {
                return ResourceManager.GetString("PlayerTab_ButtonMuteUnmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Track.
        /// </summary>
        public static string PlayerTab_ButtonNextTrack {
            get {
                return ResourceManager.GetString("PlayerTab_ButtonNextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file or list....
        /// </summary>
        public static string PlayerTab_ButtonOpen {
            get {
                return ResourceManager.GetString("PlayerTab_ButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / Pause.
        /// </summary>
        public static string PlayerTab_ButtonPlayPause {
            get {
                return ResourceManager.GetString("PlayerTab_ButtonPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Track.
        /// </summary>
        public static string PlayerTab_ButtonPrevousTrack {
            get {
                return ResourceManager.GetString("PlayerTab_ButtonPrevousTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek Back.
        /// </summary>
        public static string PlayerTab_ButtonSeekBack {
            get {
                return ResourceManager.GetString("PlayerTab_ButtonSeekBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek Forward.
        /// </summary>
        public static string PlayerTab_ButtonSeekForward {
            get {
                return ResourceManager.GetString("PlayerTab_ButtonSeekForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string PlayerTab_ButtonStop {
            get {
                return ResourceManager.GetString("PlayerTab_ButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalizer.
        /// </summary>
        public static string PlayerTab_Equalizer {
            get {
                return ResourceManager.GetString("PlayerTab_Equalizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume: {0:P1}.
        /// </summary>
        public static string PlayerTab_VolumeSliderText {
            get {
                return ResourceManager.GetString("PlayerTab_VolumeSliderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder to be added.
        /// </summary>
        public static string Playlist_AddFolderDescription {
            get {
                return ResourceManager.GetString("Playlist_AddFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Add ].
        /// </summary>
        public static string Playlist_MenuAdd {
            get {
                return ResourceManager.GetString("Playlist_MenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From directory ....
        /// </summary>
        public static string Playlist_MenuAddDirectory {
            get {
                return ResourceManager.GetString("Playlist_MenuAddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Files....
        /// </summary>
        public static string Playlist_MenuAddFile {
            get {
                return ResourceManager.GetString("Playlist_MenuAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Playlist ....
        /// </summary>
        public static string Playlist_MenuAddPlaylist {
            get {
                return ResourceManager.GetString("Playlist_MenuAddPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL ....
        /// </summary>
        public static string Playlist_MenuAddUrl {
            get {
                return ResourceManager.GetString("Playlist_MenuAddUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Disc ].
        /// </summary>
        public static string Playlist_MenuDisc {
            get {
                return ResourceManager.GetString("Playlist_MenuDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Drive found.
        /// </summary>
        public static string Playlist_MenuDiscNotfound {
            get {
                return ResourceManager.GetString("Playlist_MenuDiscNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ iTunes ].
        /// </summary>
        public static string Playlist_MenuItunes {
            get {
                return ResourceManager.GetString("Playlist_MenuItunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Manage ].
        /// </summary>
        public static string Playlist_MenuManage {
            get {
                return ResourceManager.GetString("Playlist_MenuManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear list ....
        /// </summary>
        public static string Playlist_MenuManageClear {
            get {
                return ResourceManager.GetString("Playlist_MenuManageClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string Playlist_MenuManageDelete {
            get {
                return ResourceManager.GetString("Playlist_MenuManageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save list ....
        /// </summary>
        public static string Playlist_MenuManageSave {
            get {
                return ResourceManager.GetString("Playlist_MenuManageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Sort ].
        /// </summary>
        public static string Playlist_MenuSort {
            get {
                return ResourceManager.GetString("Playlist_MenuSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-&gt;Z.
        /// </summary>
        public static string Playlist_MenuSortAsc {
            get {
                return ResourceManager.GetString("Playlist_MenuSortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-&gt;A.
        /// </summary>
        public static string Playlist_MenuSortDesc {
            get {
                return ResourceManager.GetString("Playlist_MenuSortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Playlist_MenuSortRandom {
            get {
                return ResourceManager.GetString("Playlist_MenuSortRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Discs found.
        /// </summary>
        public static string Playlist_NoDiscsFound {
            get {
                return ResourceManager.GetString("Playlist_NoDiscsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Format.
        /// </summary>
        public static string Playlist_UnsupportedListFormat {
            get {
                return ResourceManager.GetString("Playlist_UnsupportedListFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Error.
        /// </summary>
        public static string Playlist_UnsupportedListFormatTitle {
            get {
                return ResourceManager.GetString("Playlist_UnsupportedListFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian bookmarks.
        /// </summary>
        public static string Radio_RadioHungarian {
            get {
                return ResourceManager.GetString("Radio_RadioHungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Player bookmarks.
        /// </summary>
        public static string Radio_RadioTcPlayer {
            get {
                return ResourceManager.GetString("Radio_RadioTcPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Stations.
        /// </summary>
        public static string Radio_StationsLabel {
            get {
                return ResourceManager.GetString("Radio_StationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Url history ....
        /// </summary>
        public static string Settings_ClearUrlHistory {
            get {
                return ResourceManager.GetString("Settings_ClearUrlHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm exit with ESC button.
        /// </summary>
        public static string Settings_Confirm {
            get {
                return ResourceManager.GetString("Settings_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to register Multimedia keys for control.
        /// </summary>
        public static string Settings_Mediakeys {
            get {
                return ResourceManager.GetString("Settings_Mediakeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification position:.
        /// </summary>
        public static string Settings_NotificationPosition {
            get {
                return ResourceManager.GetString("Settings_NotificationPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notifications on track change.
        /// </summary>
        public static string Settings_Notify {
            get {
                return ResourceManager.GetString("Settings_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Last opened url adresses.
        /// </summary>
        public static string Settings_RememberUrl {
            get {
                return ResourceManager.GetString("Settings_RememberUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save output device on exit.
        /// </summary>
        public static string Settings_SaveDevice {
            get {
                return ResourceManager.GetString("Settings_SaveDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save volume on exit.
        /// </summary>
        public static string Settings_SaveVolume {
            get {
                return ResourceManager.GetString("Settings_SaveVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select soundfont.
        /// </summary>
        public static string Settings_SelectSoundFontTitle {
            get {
                return ResourceManager.GetString("Settings_SelectSoundFontTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_SettingLabel {
            get {
                return ResourceManager.GetString("Settings_SettingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse ....
        /// </summary>
        public static string Settings_SoundfontButton {
            get {
                return ResourceManager.GetString("Settings_SoundfontButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundFont path:.
        /// </summary>
        public static string Settings_SoundfontPath {
            get {
                return ResourceManager.GetString("Settings_SoundfontPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL History Cleared.
        /// </summary>
        public static string Settings_UrlHistoryCleared {
            get {
                return ResourceManager.GetString("Settings_UrlHistoryCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL History.
        /// </summary>
        public static string Settings_UrlHistoryClearTitle {
            get {
                return ResourceManager.GetString("Settings_UrlHistoryClearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Track #{0}.
        /// </summary>
        public static string SongData_CdTrack {
            get {
                return ResourceManager.GetString("SongData_CdTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag read error.
        /// </summary>
        public static string SongData_Error {
            get {
                return ResourceManager.GetString("SongData_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string SongData_Unknown {
            get {
                return ResourceManager.GetString("SongData_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Artist.
        /// </summary>
        public static string SongData_UnknownArtist {
            get {
                return ResourceManager.GetString("SongData_UnknownArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Song.
        /// </summary>
        public static string SongData_UnknownSong {
            get {
                return ResourceManager.GetString("SongData_UnknownSong", resourceCulture);
            }
        }
    }
}
